[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mosaiq"
version = "0.1.4"
# authors = [
#     { name = "Justin Donaldson", email = "jdonaldson@gmail.com" }
# ]
description = "A project named mosaiq"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = ["pandas", "matplotlib", "statsmodels"]
urls = { "Homepage" = "https://github.com/jdonaldson/mosaiq-python" }


[tool.setuptools.packages.find]
where = ["src"]

